import networkx as nx
import matplotlib.pyplot as plt

class Grafo:

    def main(self):
        grafo = nx.DiGraph()

        grafo.add_node("Lousado")
        grafo.add_node("Fradelos")
        grafo.add_node("Cabeçudos")
        grafo.add_node("Abade de Vermoim")
        grafo.add_node("Calendário")
        grafo.add_node("Outiz")
        grafo.add_node("Gondifelos")
        grafo.add_node("Bairro")
        grafo.add_node("Riba de Ave")
        grafo.add_node("Novais")
        grafo.add_node("Castelões")
        grafo.add_node("Mogege")
        grafo.add_node("Requião")
        grafo.add_node("Famalicão")
        grafo.add_node("Louro")
        grafo.add_node("Nine")
        grafo.add_node("Cruz")
        grafo.add_node("Arnoso (S.ta Maria)")
        grafo.add_node("Telhado")
        grafo.add_node("Joane")

        grafo.add_edge("Lousado", "Fradelos", weight=9.2)
        grafo.add_edge("Lousado", "Calendário", weight=5.7)
        grafo.add_edge("Fradelos", "Gondifelos", weight=10.2)
        grafo.add_edge("Gondifelos", "Outiz", weight=5.1)
        grafo.add_edge("Outiz", "Calendário", weight=4.2)
        grafo.add_edge("Calendário", "Abade de Vermoim", weight=6.0)
        grafo.add_edge("Abade de Vermoim", "Cabeçudos", weight=5.2)
        grafo.add_edge("Calendário", "Famalicão", weight=4.0)
        grafo.add_edge("Famalicão", "Louro", weight=5.1)
        grafo.add_edge("Louro", "Nine", weight=4.2)
        grafo.add_edge("Famalicão", "Requião", weight=5.2)
        grafo.add_edge("Requião", "Castelões", weight=8.0)
        grafo.add_edge("Mogege", "Castelões", weight=3.1)
        grafo.add_edge("Novais", "Castelões", weight=3.9)
        grafo.add_edge("Novais", "Riba de Ave", weight=4.9)
        grafo.add_edge("Novais", "Bairro", weight=3.0)
        grafo.add_edge("Famalicão", "Cruz", weight=11.4)
        grafo.add_edge("Arnoso (S.ta Maria)", "Cruz", weight=3.9)
        grafo.add_edge("Telhado", "Cruz", weight=6.2)
        grafo.add_edge("Telhado", "Joane", weight=9.0)
